export const LOGIN_REQUEST = 'AUTH/LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'AUTH/LOGIN_SUCCESS'
export const LOGIN_FAIL = 'AUTH/LOGIN_FAIL'

export const LOGOUT = 'AUTH/LOGOUT'

export const REGISTER_REQUEST = 'AUTH/REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'AUTH/REGISTER_SUCCESS'
export const REGISTER_FAIL = 'AUTH/REGISTER_FAIL'

export const PROFILE_UPDATE_REQUEST = 'AUTH/PROFILE_UPDATE_REQUEST'
export const PROFILE_UPDATE_SUCCESS = 'AUTH/PROFILE_UPDATE_SUCCESS'
export const PROFILE_UPDATE_FAIL = 'AUTH/PROFILE_UPDATE_FAIL'

export const PROFILE_GET_REQUEST = 'AUTH/PROFILE_GET_REQUEST'
export const PROFILE_GET_SUCCESS = 'AUTH/PROFILE_GET_SUCCESS'
export const PROFILE_GET_FAIL = 'AUTH/PROFILE_GET_FAIL'

export const INITIALIZE_STATUS = 'AUTH/INITIALIZE_STATUS'
