export const RECORD_LIST_REQUEST = 'RECORD/RECORD_LIST_REQUEST'
export const RECORD_LIST_SUCCESS = 'RECORD/RECORD_LIST_SUCCESS'
export const RECORD_LIST_FAIL = 'RECORD/RECORD_LIST_FAIL'

export const RECORD_DETAIL_REQUEST = 'RECORD/RECORD_DETAIL_REQUEST'
export const RECORD_DETAIL_SUCCESS = 'RECORD/RECORD_DETAIL_SUCCESS'
export const RECORD_DETAIL_FAIL = 'RECORD/RECORD_DETAIL_FAIL'

export const RECORD_NEW_REQUEST = 'RECORD/RECORD_NEW_REQUEST'
export const RECORD_NEW_SUCCESS = 'RECORD/RECORD_NEW_SUCCESS'
export const RECORD_NEW_FAIL = 'RECORD/RECORD_NEW_FAIL'

export const RECORD_UPDATE_REQUEST = 'RECORD/RECORD_UPDATE_REQUEST'
export const RECORD_UPDATE_SUCCESS = 'RECORD/RECORD_UPDATE_SUCCESS'
export const RECORD_UPDATE_FAIL = 'RECORD/RECORD_UPDATE_FAIL'

export const RECORD_DELETE_REQUEST = 'RECORD/RECORD_DELETE_REQUEST'
export const RECORD_DELETE_SUCCESS = 'RECORD/RECORD_DELETE_SUCCESS'
export const RECORD_DELETE_FAIL = 'RECORD/RECORD_DELETE_FAIL'

export const RECORD_ALL_USER_REQUEST = 'RECORD/RECORD_ALL_USER_REQUEST'
export const RECORD_ALL_USER_SUCCESS = 'RECORD/RECORD_ALL_USER_SUCCESS'
export const RECORD_ALL_USER_FAIL = 'RECORD/RECORD_ALL_USER_FAIL'
