export const USER_LIST_REQUEST = 'USER/USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER/USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER/USER_LIST_FAIL'

export const USER_DETAIL_REQUEST = 'USER/USER_DETAIL_REQUEST'
export const USER_DETAIL_SUCCESS = 'USER/USER_DETAIL_SUCCESS'
export const USER_DETAIL_FAIL = 'USER/USER_DETAIL_FAIL'

export const USER_NEW_REQUEST = 'USER/USER_NEW_REQUEST'
export const USER_NEW_SUCCESS = 'USER/USER_NEW_SUCCESS'
export const USER_NEW_FAIL = 'USER/USER_NEW_FAIL'

export const USER_UPDATE_REQUEST = 'USER/USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER/USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER/USER_UPDATE_FAIL'

export const USER_DELETE_REQUEST = 'USER/USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER/USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER/USER_DELETE_FAIL'
