export const USER_RECORD_LIST_REQUEST = 'USER_RECORD/USER_RECORD_LIST_REQUEST'
export const USER_RECORD_LIST_SUCCESS = 'USER_RECORD/USER_RECORD_LIST_SUCCESS'
export const USER_RECORD_LIST_FAIL = 'USER_RECORD/USER_RECORD_LIST_FAIL'

export const USER_RECORD_DETAIL_REQUEST = 'USER_RECORD/USER_RECORD_DETAIL_REQUEST'
export const USER_RECORD_DETAIL_SUCCESS = 'USER_RECORD/USER_RECORD_DETAIL_SUCCESS'
export const USER_RECORD_DETAIL_FAIL = 'USER_RECORD/USER_RECORD_DETAIL_FAIL'

export const USER_RECORD_NEW_REQUEST = 'USER_RECORD/USER_RECORD_NEW_REQUEST'
export const USER_RECORD_NEW_SUCCESS = 'USER_RECORD/USER_RECORD_NEW_SUCCESS'
export const USER_RECORD_NEW_FAIL = 'USER_RECORD/USER_RECORD_NEW_FAIL'

export const USER_RECORD_UPDATE_REQUEST = 'USER_RECORD/USER_RECORD_UPDATE_REQUEST'
export const USER_RECORD_UPDATE_SUCCESS = 'USER_RECORD/USER_RECORD_UPDATE_SUCCESS'
export const USER_RECORD_UPDATE_FAIL = 'USER_RECORD/USER_RECORD_UPDATE_FAIL'

export const USER_RECORD_DELETE_REQUEST = 'USER_RECORD/USER_RECORD_DELETE_REQUEST'
export const USER_RECORD_DELETE_SUCCESS = 'USER_RECORD/USER_RECORD_DELETE_SUCCESS'
export const USER_RECORD_DELETE_FAIL = 'USER_RECORD/USER_RECORD_DELETE_FAIL'
